language: java

services:
  - docker

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "thedeadc0der-github"
    token:
      secure: 3663edfe21628ccd5390b7f31df2c7dbfc70ce24

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN

before_install:
  - echo $TRAVIS_ALLOW_FAILURE
  - echo $TRAVIS_APP_HOST
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_BUILD_WEB_URL
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_DEBUG_MODE
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_JOB_NAME
  - echo $TRAVIS_JOB_NUMBER
  - echo $TRAVIS_JOB_WEB_URL
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_OSX_IMAGE
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - echo $TRAVIS_SUDO
  - echo $TRAVIS_TEST_RESULT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BUILD_STAGE_NAME
  - echo $TRAVIS_JDK_VERSION

script:
  - sonar-scanner
  - docker build -t petclinic:bigsmoke .
